### ISSUE TITLE
Check_MK 2.0 - plugin failure "inconsistent use of tabs and spaces in indentation"

### ISSUE THREAD

**Issue by randomcop** [handcode/check_mk_zvolsize#1]
After migrating from Check_MK 1.6 to 2.0 the plugin check_mk_zvolsize does not function any more.
Check_MK displays ans error message "inconsistent use of tabs and spaces in indentation" in the migration protocol and check results disappear from monitoring.

After some searching I resolved this issue by issuing the vim command ":retab" for
/omd/sites/mysite/local/share/check_mk/checks/zvolsize
to convert the tabs to spaces.

https://stackoverflow.com/questions/426963/replace-tabs-with-spaces-in-vim

**Comment by handcode** [comment]
Thanks for the hint.

I don't have a 2.0 version running yet, but I'll look into it and convert the indentations to space.

**Comment by handcode** [comment]
Fixed in 1.1

Thanks again for the hint.
